name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      run: npx vercel --prod --token $VERCEL_TOKEN --yes

    - name: Send action status to WhatsApp
      if: always()
      run: |
        branch_name="${{ github.ref }}"
        branch_name="${branch_name#refs/heads/}"
        
       
        repo_name="${{ github.repository }}"
        repo_name="${repo_name#*/}"
        
       
        short_commit_sha="${{ github.sha:0:7 }}"  # Take the first 7 characters of the commit SHA
    
        curl -X POST "https://api.twilio.com/2010-04-01/Accounts/${{ secrets.TWILIO_ACCOUNT_SID }}/Messages.json" \
          --data-urlencode "Body=$(printf 'GitHub Action CI/CD Status: %s\n\nRepository: %s\nWorkflow: %s\nBranch: %s\nCommit: %s\nCommit Message: %s\nTriggered by: %s' \
          "${{ job.status }}" \
          "$repo_name" \
          "${{ github.workflow }}" \
          "$branch_name" \
          "$short_commit_sha" \
          "${{ github.event.head_commit.message }}" \
          "${{ github.actor }}" )" \
          --data-urlencode "From=whatsapp:${{ secrets.TWILIO_WHATSAPP_NUMBER }}" \
          --data-urlencode "To=whatsapp:${{ secrets.MY_WHATSAPP_NUMBER }}" \
          -u "${{ secrets.TWILIO_ACCOUNT_SID }}:${{ secrets.TWILIO_AUTH_TOKEN }}"
