name: Deploy and Notify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      run: npx vercel --prod --token $VERCEL_TOKEN --yes

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUBUSERNAME }}
        password: ${{ secrets.DOCKERHUBTOKEN }}
    
    - name: Build & Push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUBUSERNAME }}/portfolio:latest .
        docker push ${{ secrets.DOCKERHUBUSERNAME }}/portfolio:latest