name: Deploy and Notify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Pipeline
    runs-on: ubuntu-latest
    environment:
      name: staging
      # This allows you to pause here for manual approval
      # Configure required reviewers in GitHub → Settings → Environments → staging

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUBUSERNAME }}
        password: ${{ secrets.DOCKERHUBTOKEN }}

    - name: Build & Push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUBUSERNAME }}/portfolio:latest .
        docker push ${{ secrets.DOCKERHUBUSERNAME }}/portfolio:latest

    - name: Trigger deployment on Render staging
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      run: |
        curl -X POST https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{}'

    # GitHub will pause here for manual approval if 'staging' env has required reviewers
    # No billing is incurred during this pause

    - name: Deploy to Vercel
      if: ${{ success() }}
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      run: npx vercel --prod --token $VERCEL_TOKEN --yes

    - name: Optionally delete Render staging service
      if: ${{ success() }}
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      run: |
        curl -X DELETE https://api.render.com/v1/services/$RENDER_SERVICE_ID \
          -H "Authorization: Bearer $RENDER_API_KEY"
