name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      run: npx vercel --prod --token $VERCEL_TOKEN --yes

    - name: Send CI/CD status to WhatsApp
      if: always()
      run: |
        REPO_NAME=${{ github.repository }}
        WORKFLOW_NAME=${{ github.workflow }}
        GITHUB_SHA=${{ github.sha }}
        BRANCH_NAME=${{ github.ref }}
        JOB_STATUS=${{ job.status }}
        COMMIT_MESSAGE=${{ github.event.head_commit.message }}
        ACTOR=${{ github.actor }}

        MESSAGE="GitHub Action CI/CD Status: $JOB_STATUS
        For repo: $REPO_NAME
        Workflow: $WORKFLOW_NAME
        Branch: $BRANCH_NAME
        Commit: $GITHUB_SHA
        Commit Message: $COMMIT_MESSAGE
        Triggered by: $ACTOR"

        curl -X POST https://api.twilio.com/2010-04-01/Accounts/${{ secrets.TWILIO_ACCOUNT_SID }}/Messages.json \
          --data-urlencode "Body=$MESSAGE" \
          --data-urlencode "From=whatsapp:${{ secrets.TWILIO_WHATSAPP_NUMBER }}" \
          --data-urlencode "To=whatsapp:${{ secrets.MY_WHATSAPP_NUMBER }}" \
          -u "${{ secrets.TWILIO_ACCOUNT_SID }}:${{ secrets.TWILIO_AUTH_TOKEN }}"
