name: Deploy and Notify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      run: npx vercel --prod --token $VERCEL_TOKEN --yes

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUBUSERNAME }}
        password: ${{ secrets.DOCKERHUBTOKEN }}
    
    - name: Build & Push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUBUSERNAME }}/portfolio:latest .
        docker push ${{ secrets.DOCKERHUBUSERNAME }}/portfolio:latest

    - name: Send Telegram Notification
      if: always()
      run: |
        SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
        -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
        -d parse_mode="HTML" \
        -d text="GitHub Action CI/CD Status: <b>${{ job.status }}</b>%0A
        Repository: <b>${{ github.event.repository.name }}</b>%0A
        Branch: <b>${{ github.ref_name }}</b>%0A
        Commit: <b>$SHORT_SHA</b>%0A
        Commit Message: <b>${{ github.event.head_commit.message }}</b>%0A
        Workflow: <b>${{ github.workflow }}</b>%0A
        Triggered by: <b>${{ github.actor }}</b>"
